version: "3.8"
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - TZ=Asia/Kolkata
      - GENERIC_TIMEZONE=Asia/Kolkata
    volumes:
      - n8n_:/home/node/.n8n
    restart: always
volumes:
  n8n_:
